name: "Main: Test"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  setup-test:
    runs-on: ubuntu-latest
    container: node:14.17.1
    services:
      postgres:
        image: postgres:13.3
        env:
          POSTGRES_DB: simple-task-list-db_test
          POSTGRES_PASSWORD: postgres
          POSTGRES_PORT: 2345
          POSTGRES_USER: postgres
        ports:
          - 2345:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Install PostgreSQL client
        run: |
          apt-get update
          apt-get install --yes postgresql-client

      - name: Query database
        run: psql -h postgres -d postgres_db -U postgres_user -c 'SELECT 1;'
        env:
          PGPASSWORD: postgres

      - name: Install dependencies
        run: npm install

      - name: Test with Jest
        run: npm run test
